# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_K7_APPINFO = descriptor.Descriptor(
  name='K7_AppInfo',
  full_name='K7_AppInfo',
  filename='k7talk.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='K7_AppInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='owner', full_name='K7_AppInfo.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_K7_LOGIN = descriptor.Descriptor(
  name='K7_Login',
  full_name='K7_Login',
  filename='k7talk.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='login', full_name='K7_Login.login', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='K7_Login.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_K7_USERINFO = descriptor.Descriptor(
  name='K7_UserInfo',
  full_name='K7_UserInfo',
  filename='k7talk.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='K7_UserInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_name', full_name='K7_UserInfo.first_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_name', full_name='K7_UserInfo.last_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='login', full_name='K7_UserInfo.login', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_K7_SIGNIN = descriptor.Descriptor(
  name='K7_SignIn',
  full_name='K7_SignIn',
  filename='k7talk.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='app_name', full_name='K7_SignIn.app_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='K7_SignIn.user', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_K7_BALANCEANSWER = descriptor.Descriptor(
  name='K7_BalanceAnswer',
  full_name='K7_BalanceAnswer',
  filename='k7talk.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='app', full_name='K7_BalanceAnswer.app', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='K7_BalanceAnswer.result', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_K7_USERINFO.fields_by_name['login'].message_type = _K7_LOGIN
_K7_SIGNIN.fields_by_name['user'].message_type = _K7_USERINFO
_K7_BALANCEANSWER.fields_by_name['app'].message_type = _K7_APPINFO

class K7_AppInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _K7_APPINFO

class K7_Login(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _K7_LOGIN

class K7_UserInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _K7_USERINFO

class K7_SignIn(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _K7_SIGNIN

class K7_BalanceAnswer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _K7_BALANCEANSWER


_K7TALKSERVER = descriptor.ServiceDescriptor(
  name='K7TalkServer',
  full_name='K7TalkServer',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='login',
    full_name='K7TalkServer.login',
    index=0,
    containing_service=None,
    input_type=_K7_LOGIN,
    output_type=_K7_USERINFO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='signin_app',
    full_name='K7TalkServer.signin_app',
    index=1,
    containing_service=None,
    input_type=_K7_SIGNIN,
    output_type=_K7_APPINFO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='req_increase',
    full_name='K7TalkServer.req_increase',
    index=2,
    containing_service=None,
    input_type=_K7_APPINFO,
    output_type=_K7_BALANCEANSWER,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='req_decrease',
    full_name='K7TalkServer.req_decrease',
    index=3,
    containing_service=None,
    input_type=_K7_APPINFO,
    output_type=_K7_BALANCEANSWER,
    options=None,
  ),
])

class K7TalkServer(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _K7TALKSERVER
class K7TalkServer_Stub(K7TalkServer):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _K7TALKSERVER

